### ISSUE TITLE
remove jquery dependency

### ISSUE THREAD

**Issue by lalalic** [mWater/minimongo#22]
since remoteDB support customized httpclient, is it possible to remove the must dependency on jquery, and require jquery only when there's no customized httpclient?

**Comment by lalalic** [comment]
@httpClient = httpClient or require('./jQueryHttpClient')

**Comment by grassick** [comment]
Absolutely! I'm a little busy on other work, but I would welcome a pull request.

**Comment by maxfriedmann** [comment]
I don't know why but suddenly this became an issue in one of our nativescript apps. I also don't have time right now to fix this (especially since its coffeescript), so I forked the project and removed the jquery dependency & the RemoteDb export, which was using it, see https://github.com/smallstack/minimongo

**Comment by rominf** [comment]
Because of jQuery minimongo doesn't work with Vue.js. I have an error:
```
ReferenceError: $ is not defined
```

**Comment by grassick** [comment]
I've now added a `$ = require("jquery")` (as it should have had from the beginning!)
